name: Continuous Integration Pipeline

on: [push]

jobs:
  lint-and-security-check:
    name: Lint and Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 safety

      - name: Run linter
        run: flake8 .

      - name: Check security
        run: safety check

  build-and-push:
    needs: lint-and-security-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          packer-version: '1.9.4'

      - name: Initialize Packer
        run: packer init voting-app.pkr.hcl

      - name: Format Packer configuration
        run: packer fmt voting-app.pkr.hcl

      - name: Validate Packer configuration
        run: packer validate voting-app.pkr.hcl

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image with Packer and tag
        run: |
          PACKER_LOG=1 packer build voting-app.pkr.hcl
          IMAGE_TAG=$(grep 'A docker tag was created:' packer_output.txt | cut -d' ' -f6)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myimage:${{ env.DOCKER_IMAGE_TAG }}
